# Generated by Django 5.2.17 on 2026-08-18 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('TECHNICAL', 'Technical Mock Interview'), ('HR', 'HR & Behavioral Interview')], default='TECHNICAL', max_length=30)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=45)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('technical_score', models.FloatField(default=0.0)),
                ('communication_score', models.FloatField(default=0.0)),
                ('problem_solving_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('recommendation', models.CharField(choices=[('SELECTED', 'Selected / Highly Recommended'), ('NEEDS_IMPROVEMENT', 'Needs Improvement'), ('REATTEMPT', 'Reattempt Required'), ('NOT_SELECTED', 'Not Selected')], default='NEEDS_IMPROVEMENT', max_length=30)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
