# Generated by Django 5.2.17 on 2026-08-18 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('location', models.CharField(default='San Francisco, CA', max_length=200)),
                ('work_mode', models.CharField(choices=[('ONSITE', 'Onsite'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='HYBRID', max_length=20)),
                ('salary_package', models.CharField(default='$100,000 / yr', max_length=100)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=7.0, max_digits=4)),
                ('eligible_branches', models.JSONField(blank=True, default=list)),
                ('drive_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active / Applications Open'), ('IN_PROGRESS', 'Selection Rounds in Progress'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='placement.company')),
            ],
            options={
                'ordering': ['-drive_date'],
            },
        ),
        migrations.CreateModel(
            name='DriveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('TEST_COMPLETED', 'Test Completed'), ('INTERVIEW', 'Interview Scheduled'), ('SELECTED', 'Selected / Offered'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], default='APPLIED', max_length=30)),
                ('current_round', models.CharField(default='Round 1: Online Assessment', max_length=100)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_applications', to=settings.AUTH_USER_MODEL)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placement.placementdrive')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('drive', 'student')},
            },
        ),
    ]
