# Generated by Django 5.2.17 on 2026-08-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdrive',
            name='location',
            field=models.CharField(default='Bengaluru / Hyderabad', max_length=200),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='salary_package',
            field=models.CharField(default='₹12,00,000 / yr (12 LPA)', max_length=100),
        ),
    ]
