# Generated by Django 5.2.17 on 2026-08-18 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Global Certificate Examination', max_length=200)),
                ('passing_percentage', models.FloatField(default=80.0, help_text='Configurable passing score threshold (defaults to 80%)')),
                ('max_attempts', models.IntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('course_name', models.CharField(default='Full Stack Software Engineering & Placement', max_length=255)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('score_percentage', models.FloatField(default=88.0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
