# Generated by Django 5.2.17 on 2026-08-18 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('test_type', models.CharField(choices=[('MCQ', 'MCQ Test'), ('APTITUDE', 'Aptitude Test'), ('CERTIFICATE', 'Certificate Exam')], default='MCQ', max_length=30)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('passing_percentage', models.FloatField(default=80.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(blank=True, related_name='tests', to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('total_possible', models.FloatField(default=100.0)),
                ('percentage', models.FloatField(default=0.0)),
                ('is_passed', models.BooleanField(default=False)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.test')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
